chore: fix tsc error for vm.ts
src/framework/vm.ts(66,26): error TS2345: Argument of type 'any[] | undefined' is not assignable to parameter of type 'any[]'.
  Type 'undefined' is not assignable to type 'any[]'.
src/framework/vm.ts(498,5): error TS2322: Type 'Element | null' is not assignable to type 'HTMLElement | null'.
  Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 109 more.
src/framework/vm.ts(513,37): error TS2345: Argument of type 'Element | null' is not assignable to parameter of type 'ShadowRoot | null'.
  Type 'Element' is missing the following properties from type 'ShadowRoot': host, mode, activeElement, styleSheets, and 6 more.