chore: fix tsc error for restrictions.ts
src/framework/restrictions.ts(190,61): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string, EventListener | EventListenerObject | null, (boolean | AddEventListenerOptions | undefined)?]'.
  Type 'IArguments' is missing the following properties from type '[string, EventListener | EventListenerObject | null, (boolean | AddEventListenerOptions | undefined)?]': 0, 1, pop, push, and 26 more.
src/framework/restrictions.ts(197,58): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string]'.
  Type 'IArguments' is missing the following properties from type '[string]': 0, pop, push, concat, and 25 more.
src/framework/restrictions.ts(204,61): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string]'.
src/framework/restrictions.ts(348,61): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string, EventListenerOrEventListenerObject, (boolean | AddEventListenerOptions | undefined)?]'.
  Type 'IArguments' is missing the following properties from type '[string, EventListenerOrEventListenerObject, (boolean | AddEventListenerOptions | undefined)?]': 0, 1, pop, push, and 26 more.
src/framework/restrictions.ts(400,50): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string, any]'.
  Type 'IArguments' is missing the following properties from type '[string, any]': 0, 1, pop, push, and 26 more.