chore: fix tsc error for focus.ts
src/faux-shadow/focus.ts(137,9): error TS2740: Type 'NodeListOf<Element>' is missing the following properties from type 'HTMLElement[]': pop, push, concat, join, and 24 more.
src/faux-shadow/focus.ts(148,5): error TS2322: Type 'Element | null' is not assignable to type 'HTMLElement | null'.
  Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 109 more.
src/faux-shadow/focus.ts(207,11): error TS2322: Type 'Element | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/focus.ts(219,11): error TS2322: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/focus.ts(248,11): error TS2322: Type 'Element | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/focus.ts(250,11): error TS2322: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/focus.ts(313,33): error TS2345: Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.