chore: fix tsc error for stylesheet.ts
src/framework/stylesheet.ts(27,9): error TS2339: Property 'type' does not exist on type 'HTMLElement'.
src/framework/stylesheet.ts(112,9): error TS2322: Type 'void' is not assignable to type 'VNode | null'.
src/framework/stylesheet.ts(123,55): error TS2345: Argument of type '{}' is not assignable to parameter of type 'string'.