chore: upgrade typescript from 3.1.6 to 3.3.3 (#1045)
* chore: bump typescript from 3.1.6 to 3.3.3

* chore: fix tsc error for outer-html.ts

src/3rdparty/polymer/outer-html.ts(43,46): error TS2345: Argument of type '(c: any) => "&amp;" | "&lt;" | "&gt;" | "&quot;" | "&nbsp;" | undefined' is not assignable to parameter of type '(substring: string, ...args: any[]) => string'.
  Type '"&amp;" | "&lt;" | "&gt;" | "&quot;" | "&nbsp;" | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.
src/3rdparty/polymer/outer-html.ts(47,46): error TS2345: Argument of type '(c: any) => "&amp;" | "&lt;" | "&gt;" | "&quot;" | "&nbsp;" | undefined' is not assignable to parameter of type '(substring: string, ...args: any[]) => string'.

* chore: fix tsc error for events.ts

src/faux-shadow/events.ts(62,11): error TS2322: Type 'Element | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/events.ts(119,23): error TS2322: Type 'Element | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/events.ts(213,37): error TS2345: Argument of type 'Element | null' is not assignable to parameter of type 'HTMLElement'.
  Type 'null' is not assignable to type 'HTMLElement'.

* chore: fix tsc error for focus.ts

src/faux-shadow/focus.ts(137,9): error TS2740: Type 'NodeListOf<Element>' is missing the following properties from type 'HTMLElement[]': pop, push, concat, join, and 24 more.
src/faux-shadow/focus.ts(148,5): error TS2322: Type 'Element | null' is not assignable to type 'HTMLElement | null'.
  Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 109 more.
src/faux-shadow/focus.ts(207,11): error TS2322: Type 'Element | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/focus.ts(219,11): error TS2322: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/focus.ts(248,11): error TS2322: Type 'Element | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/focus.ts(250,11): error TS2322: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'.
src/faux-shadow/focus.ts(313,33): error TS2345: Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.

* chore: fix tsc error for iframe.ts

src/faux-shadow/iframe.ts(10,47): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[any, string, (Transferable[] | undefined)?]'.
  Type 'IArguments' is missing the following properties from type '[any, string, (Transferable[] | undefined)?]': 0, 1, pop, push, and 26 more.
src/faux-shadow/iframe.ts(13,40): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[]'.
  Type 'IArguments' is missing the following properties from type '[]': pop, push, concat, join, and 24 more.
src/faux-shadow/iframe.ts(16,41): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[]'.
src/faux-shadow/iframe.ts(19,41): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[]'.

* chore: fix tsc error for shadow-root.ts

src/faux-shadow/shadow-root.ts(70,5): error TS2740: Type 'DocumentFragment' is missing the following properties from type 'SyntheticShadowRootInterface': mode, delegatesFocus, host, innerHTML, and 7 more.
src/faux-shadow/shadow-root.ts(120,17): error TS2322: Type 'Element | null' is not assignable to type 'Element'.
  Type 'null' is not assignable to type 'Element'.

* chore: fix tsc error for slot.ts

src/faux-shadow/slot.ts(72,5): error TS2740: Type '{}' is missing the following properties from type 'Node[]': length, pop, push, concat, and 26 more.
src/faux-shadow/slot.ts(81,5): error TS2322: Type '{}' is not assignable to type 'Node[]'.

* chore: fix tsc error for traverse.ts

src/faux-shadow/traverse.ts(296,5): error TS2740: Type '{}' is missing the following properties from type 'Element[]': length, pop, push, concat, and 26 more.
src/faux-shadow/traverse.ts(333,5): error TS2322: Type 'typeof PatchedHTMLIframeElement' is not assignable to type 'HTMLIFrameElementConstructor'.
  Types of property 'prototype' are incompatible.
    Type 'PatchedHTMLIframeElement' is not assignable to type 'HTMLIFrameElement'.
      Types of property 'contentWindow' are incompatible.
        Type '{ postMessage(): void; blur(): void; close(): void; focus(): void; readonly closed: boolean; readonly frames: Window; readonly length: number; location: Location; readonly opener: any; readonly parent: Window; readonly self: Window; readonly top: Window; readonly window: Window; }' is not assignable to type 'Window'.
src/faux-shadow/traverse.ts(334,13): error TS2416: Property 'contentWindow' in type 'PatchedHTMLIframeElement' is not assignable to the same property in base type 'HTMLIFrameElement'.
  Type '{ postMessage(): void; blur(): void; close(): void; focus(): void; readonly closed: boolean; readonly frames: Window; readonly length: number; location: Location; readonly opener: any; readonly parent: Window; readonly self: Window; readonly top: Window; readonly window: Window; }' is missing the following properties from type 'Window': Blob, URL, URLSearchParams, applicationCache, and 216 more.

* chore: fix tsc error for attributes.ts

src/framework/attributes.ts(193,83): error TS2345: Argument of type '"aria-"' is not assignable to parameter of type '(substring: string, ...args: any[]) => string'.

* chore: fix tsc error for base-lightning-element.ts

src/framework/base-lightning-element.ts(226,37): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string, string]'.
  Type 'IArguments' is missing the following properties from type '[string, string]': 0, 1, pop, push, and 26 more.
src/framework/base-lightning-element.ts(232,51): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string]'.
src/framework/base-lightning-element.ts(239,53): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string | null, string]'.
src/framework/base-lightning-element.ts(341,7): error TS2322: Type '{}' is not assignable to type 'PropertyDescriptorMap'.
  Index signature is missing in type '{}'.

* chore: fix tsc error for restrictions.ts

src/framework/restrictions.ts(190,61): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string, EventListener | EventListenerObject | null, (boolean | AddEventListenerOptions | undefined)?]'.
  Type 'IArguments' is missing the following properties from type '[string, EventListener | EventListenerObject | null, (boolean | AddEventListenerOptions | undefined)?]': 0, 1, pop, push, and 26 more.
src/framework/restrictions.ts(197,58): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string]'.
  Type 'IArguments' is missing the following properties from type '[string]': 0, pop, push, concat, and 25 more.
src/framework/restrictions.ts(204,61): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string]'.
src/framework/restrictions.ts(348,61): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string, EventListenerOrEventListenerObject, (boolean | AddEventListenerOptions | undefined)?]'.
  Type 'IArguments' is missing the following properties from type '[string, EventListenerOrEventListenerObject, (boolean | AddEventListenerOptions | undefined)?]': 0, 1, pop, push, and 26 more.
src/framework/restrictions.ts(400,50): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string, any]'.
  Type 'IArguments' is missing the following properties from type '[string, any]': 0, 1, pop, push, and 26 more.

* chore: fix tsc error for def.ts

src/framework/def.ts(229,7): error TS2322: Type '{}' is not assignable to type 'PropsDef'.
  Index signature is missing in type '{}'.

* chore: fix tsc error for custom-element.ts

src/faux-shadow/custom-element.ts(91,42): error TS2339: Property 'blur' does not exist on type 'Element'.

* chore: fix tsc error for services.ts

src/framework/services.ts(57,32): error TS2345: Argument of type 'ComponentInterface | undefined' is not assignable to parameter of type 'object'.
  Type 'undefined' is not assignable to type 'object'.

* chore: fix tsc error for stylesheet.ts

src/framework/stylesheet.ts(27,9): error TS2339: Property 'type' does not exist on type 'HTMLElement'.
src/framework/stylesheet.ts(112,9): error TS2322: Type 'void' is not assignable to type 'VNode | null'.
src/framework/stylesheet.ts(123,55): error TS2345: Argument of type '{}' is not assignable to parameter of type 'string'.

* chore: fix tsc error for template.ts

src/framework/template.ts(136,54): error TS2345: Argument of type 'ComponentInterface | undefined' is not assignable to parameter of type 'object'.
  Type 'undefined' is not assignable to type 'object'.

* chore: fix tsc error for vm.ts

src/framework/vm.ts(66,26): error TS2345: Argument of type 'any[] | undefined' is not assignable to parameter of type 'any[]'.
  Type 'undefined' is not assignable to type 'any[]'.
src/framework/vm.ts(498,5): error TS2322: Type 'Element | null' is not assignable to type 'HTMLElement | null'.
  Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 109 more.
src/framework/vm.ts(513,37): error TS2345: Argument of type 'Element | null' is not assignable to parameter of type 'ShadowRoot | null'.
  Type 'Element' is missing the following properties from type 'ShadowRoot': host, mode, activeElement, styleSheets, and 6 more.

* chore: fix tsc error for aria-properties/polyfill.ts

src/polyfills/aria-properties/polyfill.ts(69,86): error TS2345: Argument of type '"aria-"' is not assignable to parameter of type '(substring: string, ...args: any[]) => string'.

* chore: fix tsc error for document-shadow/polyfill.ts

src/polyfills/document-shadow/polyfill.ts(36,49): error TS2345: Argument of type 'Element | null' is not assignable to parameter of type 'Node'.
  Type 'null' is not assignable to type 'Node'.
src/polyfills/document-shadow/polyfill.ts(39,17): error TS2531: Object is possibly 'null'.

* chore: fix tsc error for assert.ts

src/shared/assert.ts(98,73): error TS2345: Argument of type '"\n"' is not assignable to parameter of type '{ [Symbol.split](string: string, limit?: number | undefined): string[]; }'.

* chore: fix tsc error for property-trap.ts

* chore: review feedback

* chore: review feedback

* chore: introduce UninitializedVM interface

* chore: review feedback

* fix: test failures