chore: fix tsc error for iframe.ts
src/faux-shadow/iframe.ts(10,47): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[any, string, (Transferable[] | undefined)?]'.
  Type 'IArguments' is missing the following properties from type '[any, string, (Transferable[] | undefined)?]': 0, 1, pop, push, and 26 more.
src/faux-shadow/iframe.ts(13,40): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[]'.
  Type 'IArguments' is missing the following properties from type '[]': pop, push, concat, join, and 24 more.
src/faux-shadow/iframe.ts(16,41): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[]'.
src/faux-shadow/iframe.ts(19,41): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[]'.