chore: fix tsc error for traverse.ts
src/faux-shadow/traverse.ts(296,5): error TS2740: Type '{}' is missing the following properties from type 'Element[]': length, pop, push, concat, and 26 more.
src/faux-shadow/traverse.ts(333,5): error TS2322: Type 'typeof PatchedHTMLIframeElement' is not assignable to type 'HTMLIFrameElementConstructor'.
  Types of property 'prototype' are incompatible.
    Type 'PatchedHTMLIframeElement' is not assignable to type 'HTMLIFrameElement'.
      Types of property 'contentWindow' are incompatible.
        Type '{ postMessage(): void; blur(): void; close(): void; focus(): void; readonly closed: boolean; readonly frames: Window; readonly length: number; location: Location; readonly opener: any; readonly parent: Window; readonly self: Window; readonly top: Window; readonly window: Window; }' is not assignable to type 'Window'.
src/faux-shadow/traverse.ts(334,13): error TS2416: Property 'contentWindow' in type 'PatchedHTMLIframeElement' is not assignable to the same property in base type 'HTMLIFrameElement'.
  Type '{ postMessage(): void; blur(): void; close(): void; focus(): void; readonly closed: boolean; readonly frames: Window; readonly length: number; location: Location; readonly opener: any; readonly parent: Window; readonly self: Window; readonly top: Window; readonly window: Window; }' is missing the following properties from type 'Window': Blob, URL, URLSearchParams, applicationCache, and 216 more.