chore: fix tsc error for base-lightning-element.ts
src/framework/base-lightning-element.ts(226,37): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string, string]'.
  Type 'IArguments' is missing the following properties from type '[string, string]': 0, 1, pop, push, and 26 more.
src/framework/base-lightning-element.ts(232,51): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string]'.
src/framework/base-lightning-element.ts(239,53): error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[string | null, string]'.
src/framework/base-lightning-element.ts(341,7): error TS2322: Type '{}' is not assignable to type 'PropertyDescriptorMap'.
  Index signature is missing in type '{}'.