chore: fix tsc error for slot.ts
src/faux-shadow/slot.ts(72,5): error TS2740: Type '{}' is missing the following properties from type 'Node[]': length, pop, push, concat, and 26 more.
src/faux-shadow/slot.ts(81,5): error TS2322: Type '{}' is not assignable to type 'Node[]'.