chore: fix tsc error for shadow-root.ts
src/faux-shadow/shadow-root.ts(70,5): error TS2740: Type 'DocumentFragment' is missing the following properties from type 'SyntheticShadowRootInterface': mode, delegatesFocus, host, innerHTML, and 7 more.
src/faux-shadow/shadow-root.ts(120,17): error TS2322: Type 'Element | null' is not assignable to type 'Element'.
  Type 'null' is not assignable to type 'Element'.