chore: fix tsc error for def.ts
src/framework/def.ts(229,7): error TS2322: Type '{}' is not assignable to type 'PropsDef'.
  Index signature is missing in type '{}'.